#!/usr/bin/php
<?php
require_once('/etc/munin/oscam_conf.php');
require_once(dirname(__FILE__).'/oscam_class.php');
//#################################################################
$osc = new OSCam;
$peer = $osc->muninGetMulti(basename(__FILE__));
$osc->muninPlugin('peers-online',$peer);
?>